language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-21
    - android-27
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew
install:
 - yes | sdkmanager tools
 - yes | sdkmanager "system-images;android-21;default;armeabi-v7a"
 - echo no | avdmanager create avd --force -n test -k "system-images;android-21;default;armeabi-v7a"
 - $ANDROID_HOME/emulator/emulator -avd test -skin 1080x1920 -no-audio -no-window &
script:
 - android-wait-for-emulator
 - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
 - ./gradlew clean jacocoTestReport --stacktrace
after_success:
 - bash <(curl -s https://codecov.io/bash)
