language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-26.0.3
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-26
    - android-27
    
    - sys-img-x86-google_apis-26
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew
 - yes | sdkmanager "platforms;android-26"
script:
 - android list targets
 - android list sdk --extended --no-ui --all
 - echo no | android create avd --force -n test --package "system-images;android-26;google_apis;x86"
# - emulator -avd test -no-window &
# - android-wait-for-emulator
# - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
# - ./gradlew clean jacocoTestReport
after_success:
 - bash <(curl -s https://codecov.io/bash)
